services:
  - type: web
    name: ibm-attrition_model
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run model_applying.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9