services:
  - type: web
    name: ibm-hr-attrition_model
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run model_applying.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 # <--- AQUI você define a versão