services:
  - type: web
    name: ibm-attrition_model
  env: python                # <-- campo correto (sem "runtime")
    plan: free
    pythonVersion: 3.11.9    # <-- versÃ£o fixada de forma direta
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run model_applying.py --server.port $PORT --server.address 0.0.0.0